In [5]:
import pandas as pd
df = pd.read_csv('E0.csv')
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10

In [6]:
df.shape

(380, 120)

In [7]:
matches = df[['Date','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']]
matches.head()

         Date    HomeTeam     AwayTeam  FTHG  FTAG FTR
0  16/08/2024  Man United       Fulham     1     0   H
1  17/08/2024     Ipswich    Liverpool     0     2   A
2  17/08/2024     Arsenal       Wolves     2     0   H
3  17/08/2024     Everton     Brighton     0     3   A
4  17/08/2024   Newcastle  Southampton     1     0   H

In [8]:
matches['FTR'].value_counts()

FTR
H    155
A    132
D     93
Name: count, dtype: int64

In [9]:
home_points_map = {'H' : 3, 'D' : 1, 'A' : 0}
matches['home_points'] = matches['FTR'].map(home_points_map)
matches.head()

         Date    HomeTeam     AwayTeam  FTHG  FTAG FTR  home_points
0  16/08/2024  Man United       Fulham     1     0   H            3
1  17/08/2024     Ipswich    Liverpool     0     2   A            0
2  17/08/2024     Arsenal       Wolves     2     0   H            3
3  17/08/2024     Everton     Brighton     0     3   A            0
4  17/08/2024   Newcastle  Southampton     1     0   H            3

In [10]:
away_points_map = {'H' : 0, 'D' : 1, 'A' : 3}
matches['away_points'] = matches['FTR'].map(away_points_map)
matches.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,home_points,away_points
0,16/08/2024,Man United,Fulham,1,0,H,3,0
1,17/08/2024,Ipswich,Liverpool,0,2,A,0,3
2,17/08/2024,Arsenal,Wolves,2,0,H,3,0
3,17/08/2024,Everton,Brighton,0,3,A,0,3
4,17/08/2024,Newcastle,Southampton,1,0,H,3,0

In [11]:
home_pts = matches.groupby('HomeTeam')['home_points'].sum()
home_pts

HomeTeam
Arsenal           39
Aston Villa       40
Bournemouth       28
Brentford         31
Brighton          32
Chelsea           41
Crystal Palace    25
Everton           24
Fulham            26
Ipswich            7
Leicester         15
Liverpool         46
Man City          42
Man United        24
Newcastle         38
Nott'm Forest     32
Southampton        6
Tottenham         21
West Ham          20
Wolves            21
Name: home_points, dtype: int64

In [12]:
away_pts = matches.groupby('AwayTeam')['away_points'].sum()
away_pts

AwayTeam
Arsenal           35
Aston Villa       26
Bournemouth       28
Brentford         25
Brighton          29
Chelsea           28
Crystal Palace    28
Everton           24
Fulham            28
Ipswich           15
Leicester         10
Liverpool         38
Man City          29
Man United        18
Newcastle         28
Nott'm Forest     33
Southampton        6
Tottenham         17
West Ham          23
Wolves            21
Name: away_points, dtype: int64

In [13]:
total_pts = (home_pts + away_pts).sort_values(ascending=False)
total_pts

HomeTeam
Liverpool         84
Arsenal           74
Man City          71
Chelsea           69
Aston Villa       66
Newcastle         66
Nott'm Forest     65
Brighton          61
Brentford         56
Bournemouth       56
Fulham            54
Crystal Palace    53
Everton           48
West Ham          43
Man United        42
Wolves            42
Tottenham         38
Leicester         25
Ipswich           22
Southampton       12
dtype: int64

In [14]:
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10